todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskIsDoneView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/task-is-done/",
        TaskIsDoneView.as_view(),
        name="task-is-done"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list"

todo_list_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
    path("__debug__/", include("debug_toolbar.urls")),
]

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    creation_time = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)

    class Meta:
        ordering = ["is_done", "-creation_time"]

    def __str__(self):
        return self.content

todo_list/forms.py
from django import forms

from todo_list.models import Tag, Task


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "YYYY-MM-DD hh:mm:ss"})
    )
    tags = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

todo_list/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo_list/index.html"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:index")


class TaskIsDoneView(generic.View):
    def get(self, request):
        return HttpResponseRedirect(reverse_lazy("todo_list:index"))

    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk)
        task.is_done = not task.is_done
        task.save()

        return HttpResponseRedirect(reverse_lazy("todo_list:index"))


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid mt-4">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>

        <div class="col-sm-10">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group font-weight-bold">
  <li class="list-group-item"><a href="{% url 'todo_list:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}">Tags</a></li>
</ul>

templates/todo_list/index.html
{% extends "base.html" %}

{% block content %}
  <h1 class="mb-4 d-flex align-items-center">
    TODO list
    <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary btn-lg ml-auto">Add task</a>
  </h1>
  <hr>

  {% if task_list %}
    {% for task in task_list %}
      <h5 class="pb-2 font-weight-bold">
        {{ task.content }}

        {% if task.is_done %}
          <span class="text-success"> Done</span>
          <form action="{% url 'todo_list:task-is-done' pk=task.id%}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary btn-lg float-right">Undo</button>
          </form>
        {% else %}
          <span class="text-danger">Not Done</span>
          <form action="{% url 'todo_list:task-is-done' pk=task.id%}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-lg float-right">Complete</button>
          </form>
        {% endif %}
      </h5>

      <p>Created: {{ task.creation_time }}
        {% if task.deadline %}
          <span class="text-danger">Deadline: {{ task.deadline }}</span>
        {% endif %}
      </p>

      <h5 class="text-secondary">
        Tags:
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% empty %}
          none
        {% endfor %}
        <span>
          <a href="{% url 'todo_list:task-update' pk=task.id%}">Update</a>
          <a href="{% url 'todo_list:task-delete' pk=task.id%}">Delete</a>
        </span>
      </h5>
      <hr>
    {% endfor %}

  {% else %}
    <h5>There are no tasks in todo list</h5>
  {% endif %}
{% endblock %}

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2 class="mb-2">Delete <span class="text-muted">{{ tag.name }}</span>?</h2>
  <p>Are you sure you want to delete this tag?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, I am sure." class="btn btn-danger">
    <a href="{% url 'todo_list:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2 class="mb-2">{{ object|yesno:"Update,Create" }} Tag</h2>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
    <a href="{% url 'todo_list:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="mb-4 d-flex align-items-center">
    Tags
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary btn-lg ml-auto">Add tag</a>
  </h1>

  {% if tag_list %}
    <table class="table table-hover">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url 'todo_list:tag-update' pk=tag.id%}" class="btn btn-secondary">Update</a></td>
          <td><a href="{% url 'todo_list:tag-delete' pk=tag.id%}" class="btn btn-secondary">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <h5>There are no tags in todo list</h5>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2 class="mb-2">Delete <span class="text-muted">{{ task.content }}</span>?</h2>
  <p>Are you sure you want to delete this task?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, I am sure." class="btn btn-danger">
    <a href="{% url 'todo_list:index' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2 class="mb-2">{{ object|yesno:"Update,Create" }} Task</h2>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="Submit">
    <a href="{% url 'todo_list:index' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}